# -*- coding: utf-8 -*-
"""1_M3_Python_Basic_start.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYVr3P5DuZjE_-NAcIIj43ZPQlhRW3lE
"""

x=1+2

x

print(x)



"""## Output"""

print("Hello world!")

print("My country is India")

print("sum=",x)

"""## comments"""

print("Alma x students")
# this is a print statements

"""## Variables"""

my_var="Rahul"
my_var2="John"

print(my_var2)

# 2_my_var="Alma"

_my_var="alma"

"""## Data types"""

## Text type:str

x="Hello world"
print(x)

print(type(x))

#int data type
y=1
print(y)
print(type(y))

#float data type
z=2.4
print(z)
print(type(z))

#list data type ,it is mutable
x=["apple","banana","guava"]
print(x)
print(type(x))

x.append("oranage")
print(x)

#tuple is immutable
z=("apple","cherry","plum")
print(z)

print(type(z))
# z.append("orange")

z=["alma",1]
print(z)

#dictionary data type
y={"name":"john","age":19}
print(y)

print(type(y))

print(y['name'])

print(y['age'])

for key,value in y.items():
  print(key)
  print(value)

# set-it will have unique values
z={"apple","orange","guava"}
print(z)
print(type(z))

z={"apple","orange","guava","orange"}
print(z)

# boolean data type
a=True

b=False

print(a,b)

"""## Operators"""

x=20
y=4

print(x+y)

z=x+y
print(z)

z=x*y
print(z)

z=x/y
print(z)

z=x-y
print(z)

z=x//y
print(z)

z=x%y
print(z)

z=(2+28)/5 #BODMAS
print(z)

"""## If else"""

x=20
y=20
if x>=y:
  print("x is greater then equal y")
else:
  print("x is smaller then y")

x=30
y=20
if x>=y:
  print("x is greater then equal y")
else:
  print("x is smaller then y")

## Elif

x=10
y=20
z=15

if x>y:
  print("x is greater then y")
elif y>z:
  print("y is greater then z")

x=10
y=10
if x>y:
  print("x is greater then y")
elif y>x:
  print("y is greater then x")
else:
  print("x and y is equal")

"""## Activity"""

z=["apple","orange","guava"]
print(z)

print(z[1])

print(z[0])

print(z[-1])

x="Delhi is capital of India"
print(x)

print(x[0:5])

print(x[7::])



# print(x[::1])

x="Delhi is capital of India"
z=x.split(" ")
print(z)

for index in range(len(z)):
   print(z[len(z)-index-1])

"""## Input"""

name=input("type your name")

print(name)

age=input("enter your age")
print(age)
print(type(age))

age=int(age)

print(age)
print(type(age))

z=[4,245,2,23,12]
print(z)

y=sorted(z)
print(y)

a_min=min(y)
b=max(y)
print(a_min,b)

z.remove(23)

print(z)



"""## Built in functions"""

x=42
print(type(x))
my_string=str(42)
print(type(my_string))

print(my_string)

a="2.224"
print(a)
z=float(a)
print(z)

my_list=list([1,4,2,1])
print(my_list)

print(len(my_list))

sorted_list=sorted(my_list)
print(sorted_list)

second_list=[34,56,23,38]
combined_list=list(zip(my_list,second_list))
print(combined_list)

my_list.append(10)
print(my_list)

append_list=my_list.append(10)
print(append_list)

append_list=my_list
print(append_list)

sorted_list=sorted(my_list,reverse=True)
print(sorted_list)

append_list